### PR TITLE
WIP: Solitaire

### PR DESCRIPTION
**Pull request by IgorMacGregor**
I have created the view of the solitaire game, which is not yet playable. Before adding the game logic + the control events, I wanted to be sure that I have constructed it well as I'm pretty new to GitHub. I didn't use Hooks, is it a problem ? If so, I will change that as soon as possible.
Thanks ! :)

### CODE REVIEW

**Comment by IgorMacGregor** [comment]
After a day spent on hooks and trying to change my commit, I will soon be able to commit a hooked-version ! :)

**Comment by maracuja-juice** [comment]
Nice!
btw, you should use yarn for this repo and delete the package-lock.json again.

**Comment by ghostslayer989** [comment]
I sadly can't fix those conflicts due to not having permission to do so.

**Comment by IgorMacGregor** [comment]
Hi guys, I have achieved to switch to Hooks with npm on an older version of the project. Now that I have switched to Yarn and pulled the most recent verion, I have some errors due to the new winXP/src/WinXP/Footer/index.js and winXP/src/WinXP/Windows/index.js files, and I don't see the link with the Solitaire program that I am implementing ... Should I commit anyway ?

**Comment by ShizukuIchi** [comment]
Great work @IgorMacGregor! 
Some code changed after you started implementing Solitaire. You need to pull the newest version, merge, fix conflict.

**Pull request closed without merging**
