### PR TITLE
add error sound

### PR DESCRIPTION
**Pull request by ShizukuIchi**

### CODE REVIEW

**Comment by ShizukuIchi** [comment]
#62

**Comment by maracuja-juice** [comment]
This is the exact modification I imagined, it fixes the concerns from #62.
I'm pretty sure it won't work in Safari and other browsers (mobile chrome) that restrict playing of sounds to be a result of a user interaction. I think the code modifications needed for that would be a lot bigger though and as this is just an enhancement I think it's good enough. (but I don't know this code base really well)

TL;DR: This is great!

**Comment by ghostslayer989** [comment]
Well, don't users have to use the website in order to activate the error sound? So isn't the website interacted with?

**Comment by maracuja-juice** [comment]
@ghostslayer989 The restriction is that it must be called from an onClick Handler.

**Comment by maracuja-juice** [comment]
Small follow up to illustrate what I mean:
`Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.` (Safari)
But as I said before this is fine.

**Comment by maracuja-juice** [comment]
How difficult would it be though to move the sound handling directly into the onClick handler?

**Pull request merged**
