### PR TITLE
draft: implement error sound for error box

### PR DESCRIPTION
**Pull request by maracuja-juice**
Based on #50 I fixed the bug for the playing of the error sound using Hooks and State.

Addresses #39

Credit to @ghostslayer989 for implementing the initial sound version.

### CODE REVIEW

**Comment by ghostslayer989** [comment]
Horosho!

**Comment by ghostslayer989** [comment]
It erm doesn't work, dragging the errorbox causes errrrrrrrrrrrrrrr

**Comment by maracuja-juice** [comment]
I didn't have that behaviour in Chrome. What's your setup?

**Comment by maracuja-juice** [comment]
You're right. Weird that it worked yesterday when testing it.. I'll need to try again sometime.

**Comment by maracuja-juice** [comment]
When you immediately move the window the method doesn't work.
But if you wait until the sound playing is finished everything works like it should.

Not sure yet how to resolve this.

**Comment by ghostslayer989** [comment]
I get a chuckle out of the dragging bug but I know it is... well, a bug.

**Comment by maracuja-juice** [comment]
Were you able to confirm that it works though when you wait until is finished and then drag though?

**Comment by ghostslayer989** [comment]
Yep that part works atleast. _errrrrrrrrrrrrrrrrrr_

**Comment by ghostslayer989** [comment]
Dududu deploying time.

**Comment by ghostslayer989** [comment]
Dududu works for me!

**Comment by maracuja-juice** [comment]
Has to be something into this direction but it's not perfect yet. Sometimes it's too short and if you're fast enough you can still trigger it.
Maybe react-sound is not the best solution and we should use the normal Audio API + useEffect Hook.
I will try this out sometime later this week.

**Comment by ghostslayer989** [comment]
Some of my friends said to make it only play on mount and wait until it's unmounted then mounted again to play.

**Comment by maracuja-juice** [comment]
That what I'm saying with the useEffect Hook + Audio API. I think you can't do that with React-Sound.

**Comment by ghostslayer989** [comment]
Ah. I'm not sharpest React Dev in the shed.

**Comment by ShizukuIchi** [comment]
I prefer not to use package. I'll make a test version later.

**Comment by maracuja-juice** [comment]
@ShizukuIchi I will have a bit of time this evening to try it out with the Audio API.

**Pull request closed without merging**
