### PR TITLE
Run command box

### PR DESCRIPTION
**Pull request by PunyaChapagain**
Run command box command when you click run from the start.

### CODE REVIEW

**Comment by maracuja-juice** [comment]
Any specifc reason why you closes this and your other PR?

**Comment by PunyaChapagain** [comment]
I thought may be my pull request is not accepted.  Let me know if I am wrong

**Comment by ShizukuIchi** [comment]
Hey @PunyaChapagain,
I noticed that there is some different behaviors between Error, Run.. and other apps so I'm figuring out to refactor some code. That's why I didn't accept the PR.  Thank you.

**Comment by PunyaChapagain** [comment]
ya I was trying to make it look real without keeping minimise and maximise button in error and runbox  and adding help button. or I can push as it is with those min and max button.

**Comment by ShizukuIchi** [comment]
I think it's not appropriate enough to put (title !== "Run") && there. There might be other apps having special buttons set.

**Pull request closed without merging**
