### PR TITLE
ErrorBox Sound

### PR DESCRIPTION
**Pull request by ghostslayer989**
I made the ErrorBox sound but there are some issues I can't figure out how to fix.
(spawn a Error Message and switch between windows in winxp. Start -> Windows Messenger)

### CODE REVIEW

**Comment by ghostslayer989** [comment]
Fixable if sound implemented around here? https://github.com/ghostslayer989/winXP/blob/master/src/WinXP/index.js#L273

**Comment by maracuja-juice** [comment]
Not sure. But I would really recommend that you test your changes in a local environment because it doesn't seem like you do. This will help you to speed up things greatly :)

**Comment by ghostslayer989** [comment]
I do. But this Audio bug is confusing me.

**Comment by maracuja-juice** [comment]
On every render you are saying that you want to play the Sound. I'll give it a try to only do it one time now.

**Comment by maracuja-juice** [comment]
What I think should work is something like this:

```
class Error extends React.Component {

  constructor(props) {
    super(props);
    this.state = {soundWasPlayed: false};
  }

  componentDidMount() {
    this.setState({soundWasPlayed: true});
  }

  render() {
    const {soundWasPlayed} = this.state;

    return (
        <Div>
          {!soundWasPlayed &&
          <Sound
              url={errorsound}
              playStatus={Sound.status.PLAYING}
              playFromPosition={0}
          />
          }
          <div className="error__top">
            <img src={error} alt="error" className="error__img" />
            <div className="error__messages">{lineBreak(this.props.message)}</div>
          </div>
          <div className="error__bottom">
            <div onClick={this.props.onClose} className="error__button">
              <span className="error__confirm">OK</span>
            </div>
          </div>
        </Div>
    );
  }
}
```

Problem now is that as this is now a class (otherwise you can't use lifecycle methods) this won't render anymore because it is called like a function in `Windows/index.js`:

```
      <div className="app__content">
        {component({
          onClose: _onMouseUpClose,
          onMinimize: _onMouseUpMinimize,
          isFocus,
          ...injectProps,
        })}
      </div>
```

I didn't figure out how to fix that to actually test the new approach.

**Comment by maracuja-juice** [comment]
I fixed it. Found out that you can use hooks to manipulate state: https://reactjs.org/docs/hooks-state.html

**Pull request closed without merging**
