### PR TITLE
Win XP error sound

### PR DESCRIPTION
**Pull request by ghostslayer989**
Gonna use Now bot to test it.

### CODE REVIEW

**Comment by ghostslayer989** [comment]
package.json?

**Comment by ghostslayer989** [comment]
I never even touched you package.json

**Comment by ghostslayer989** [comment]
erm.

**Comment by maracuja-juice** [comment]
I think this file either has to be in the public folder or what could work too is to add an import. Otherwise it won't be included in the bundle.

What is the problem exactly?

**Comment by ghostslayer989** [comment]
Now Bot: (Deployment has failed.)
Now Bot/package.json (has failed)

**Comment by ghostslayer989** [comment]
Gonna make a new branch

**Comment by maracuja-juice** [comment]
Ah I see the problem now. Didn't see it on mobile.
Does now provide a more specific error message somewhere?

**Comment by ghostslayer989** [comment]
Not that I see. Zeit.co says I don't have perms to see build errors.

**Comment by maracuja-juice** [comment]
@Shizukulchi can probably tell you more.

**Comment by ghostslayer989** [comment]
@ShizukuIchi Got any info if not currently asleep due to timezones?

**Comment by ShizukuIchi** [comment]
syntax error.
you should build and test it in local before making a PR

**Comment by maracuja-juice** [comment]
I think it is because embed is not closed.

**Comment by ghostslayer989** [comment]
I might've deleted some other code accidentally. Gonna do a new branch.

**Comment by ghostslayer989** [comment]
...Does ReactJS even allow embeds?

**Comment by ghostslayer989** [comment]
I believe I have to import some stuff in order to even play audio.

**Comment by ShizukuIchi** [comment]
Hello @ghostslayer989,
you need to clone the project to your computer and run `yarn && yarn start` to test your code

**Pull request closed without merging**
